### PR TITLE
fix(execa): use `await execa` instead of `execaSync` since it produces unexpected errors when spawning git commands - fixes #17

### LINKED ISSUE #17: Failed to backmerge branches.: xJ: Command failed with ENOENT: git fetch
We are running in to a rather odd issue with this plugin. In one particular project the backmerges always fail with:

```
Failed to backmerge branches.

xJ: Command failed with ENOENT: git fetch 'https://gitlab-ci-token:[secure]@gitlab.com/REDACTED' spawnSync git ENOENT
```

We have `GITLAB_TOKEN` set as Masked+Hidden variable. The token itself is fine, since `semantic-release/gitlab` can create releases + tags just fine using it.
Git is installed in the container as well:

```bash
~ # git --version
git version 2.45.2
```

Relevant part of `.releaserc.js`:

```js
    [
      "@kilianpaquier/semantic-release-backmerge",
      {
        targets: [
          { from: "production", to: "develop" },
          { from: "acceptance", to: "develop" }
        ],
        title: "ci(release): fix mergeback from ${ from } into ${ to } [skip ci]",
      }
    ],
```

Logs:

```bash
[8:16:48 AM] [semantic-release] › ℹ  Start step "success" of plugin "@kilianpaquier/semantic-release-backmerge"
[8:16:48 AM] [semantic-release] [@kilianpaquier/semantic-release-backmerge] › ℹ  Current branch 'acceptance' matches following configured backmerge targets: '[{"from":"acceptance","to":"develop"}]'. Performing backmerge.
[8:16:48 AM] [semantic-release] › ✘  Failed step "success" of plugin "@kilianpaquier/semantic-release-backmerge"
[8:16:48 AM] [semantic-release] › ℹ  Start step "fail" of plugin "@semantic-release/gitlab"
[8:16:49 AM] [semantic-release] [@semantic-release/gitlab] › ℹ  Commented on issue REDACTED: https://gitlab.com/REDACTED/-/issues/X.
[8:16:49 AM] [semantic-release] › ✔  Completed step "fail" of plugin "@semantic-release/gitlab"
[8:16:49 AM] [semantic-release] › ℹ  Start step "fail" of plugin "semantic-release-slack-bot"
[8:16:49 AM] [semantic-release] [semantic-release-slack-bot] › ℹ  Notifying on fail skipped
[8:16:49 AM] [semantic-release] › ✔  Completed step "fail" of plugin "semantic-release-slack-bot"
[8:16:49 AM] [semantic-release] › ✘  EBACKMERGE Failed to backmerge branches.
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'marked-terminal' imported from /usr/local/lib/node_modules/semantic-release/index.js
    at packageResolve (node:internal/modules/esm/resolve:854:9)
    at moduleResolve (node:internal/modules/esm/resolve:927:18)
    at defaultResolve (node:internal/modules/esm/resolve:1169:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:542:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:510:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:239:38)
    at ModuleLoader.import (node:internal/modules/esm/loader:472:34)
    at defaultImportModuleDynamicallyForModule (node:internal/modules/esm/utils:214:31)
    at importModuleDynamicallyCallback (node:internal/modules/esm/utils:253:12)
    at terminalOutput (file:///usr/local/lib/node_modules/semantic-release/index.js:29:43) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

I have tried to reproduce the issue in a separate repository, but for the backmerges seem to work fine there. They both use the same config in `.releaserc.js`. Is there a way to get more logging out of this plugin to see what it is actually doing and why it is failing?

### LINKED ISSUE #19: Avoid trying to recreate a pull request between two branches when one already exists
While investigating another issue, when trying to create a pull request between two branches when one already exists an exception is thrown:

https://gitlab.com/kilianpaquier/semantic-release-testing/-/jobs/8152217953

To avoid this issue, plugin should first test if a pull request is already opened before trying to create a pull request.

### PR DESCRIPTION
**Pull request by kilianpaquier**
Fixes both #17 and #20

### CODE REVIEW

**Comment by kilianpaquier** [comment]
Hi @syphernl, is it OK on your end with this code ? I'm gonna add the debug logs in another commit.

**Comment by kilianpaquier** [comment]
Uses most of produced code from here https://github.com/kilianpaquier/semantic-release-backmerge/pull/24

**Comment by syphernl** [comment]
> Hi @syphernl, is it OK on your end with this code ? I'm gonna add the debug logs in another commit.

Applied these changes on my test env, no `git` errors regarding `ENOENT` anymore so in that regard it seems to be working.
Still getting the "Updates were rejected because the tip of your current branch is behind" but that will be handled in #23

**Comment by kilianpaquier** [comment]
Great, I'm gonna add debug logs and check this `tip` issue afterhand but in another PR

**Pull request merged**
